[
 

  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9861551',
      name: 'Black Blackmeans Edition Jeans',
      brand: {
        '@type': 'Brand',
        name: 'alyx',
      },
      offers: {
        '@type': 'Offer',
        price: 760,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alyx/black-blackmeans-edition-jeans/9861551',
      },
      url: '/men/product/alyx/black-blackmeans-edition-jeans/9861551',
      image: 'https://img.ssensemedia.com/images/222776M186001_1/alyx-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alyx/black-blackmeans-edition-jeans/9861551',
    's-text': '1017 ALYX 9SM',
    's-text 2': 'Black Blackmeans Edition Jeans',
    's-text 3': '$760',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954051',
      name: 'White Viscose Blazer',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 3245,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-viscose-blazer/9954051',
      },
      url: '/men/product/alexander-mcqueen/white-viscose-blazer/9954051',
      image: 'https://img.ssensemedia.com/images/222259M195002_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-viscose-blazer/9954051',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Viscose Blazer',
    's-text 3': '$3245',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9953901',
      name: 'Pink Wool Blazer',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 2490,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/pink-wool-blazer/9953901',
      },
      url: '/men/product/alexander-mcqueen/pink-wool-blazer/9953901',
      image: 'https://img.ssensemedia.com/images/222259M195001_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/pink-wool-blazer/9953901',
    's-text': 'Alexander McQueen',
    's-text 2': 'Pink Wool Blazer',
    's-text 3': '$2490',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954091',
      name: 'White Workwear Denim Jacket',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1570,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-workwear-denim-jacket/9954091',
      },
      url: '/men/product/alexander-mcqueen/white-workwear-denim-jacket/9954091',
      image: 'https://img.ssensemedia.com/images/222259M180000_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-workwear-denim-jacket/9954091',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Workwear Denim Jacket',
    's-text 3': '$1570',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954121',
      name: 'Black Polyester Jacket',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1110,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-polyester-jacket/9954121',
      },
      url: '/men/product/alexander-mcqueen/black-polyester-jacket/9954121',
      image: 'https://img.ssensemedia.com/images/222259M180001_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-polyester-jacket/9954121',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Polyester Jacket',
    's-text 3': '$1110',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954161',
      name: 'White Cotton Sweatshirt',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 590,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-cotton-sweatshirt/9954161',
      },
      url: '/men/product/alexander-mcqueen/white-cotton-sweatshirt/9954161',
      image: 'https://img.ssensemedia.com/images/222259M204000_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-cotton-sweatshirt/9954161',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Cotton Sweatshirt',
    's-text 3': '$590',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954231',
      name: 'Blue Cotton Shirt',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1040,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/blue-cotton-shirt/9954231',
      },
      url: '/men/product/alexander-mcqueen/blue-cotton-shirt/9954231',
      image: 'https://img.ssensemedia.com/images/222259M192009_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/blue-cotton-shirt/9954231',
    's-text': 'Alexander McQueen',
    's-text 2': 'Blue Cotton Shirt',
    's-text 3': '$1040',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954821',
      name: 'Blue Graffiti Harness Shirt',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 640,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/blue-graffiti-harness-shirt/9954821',
      },
      url: '/men/product/alexander-mcqueen/blue-graffiti-harness-shirt/9954821',
      image: 'https://img.ssensemedia.com/images/222259M192018_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/blue-graffiti-harness-shirt/9954821',
    's-text': 'Alexander McQueen',
    's-text 2': 'Blue Graffiti Harness Shirt',
    's-text 3': '$640',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9953961',
      name: 'White Cotton Shirt',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 850,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-cotton-shirt/9953961',
      },
      url: '/men/product/alexander-mcqueen/white-cotton-shirt/9953961',
      image: 'https://img.ssensemedia.com/images/222259M192001_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-cotton-shirt/9953961',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Cotton Shirt',
    's-text 3': '$850',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954111',
      name: 'White Printed Jeans',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 870,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-printed-jeans/9954111',
      },
      url: '/men/product/alexander-mcqueen/white-printed-jeans/9954111',
      image: 'https://img.ssensemedia.com/images/222259M186002_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-printed-jeans/9954111',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Printed Jeans',
    's-text 3': '$870',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954251',
      name: 'Navy Recycled Polyester Cargo Pants',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1345,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/navy-recycled-polyester-cargo-pants/9954251',
      },
      url: '/men/product/alexander-mcqueen/navy-recycled-polyester-cargo-pants/9954251',
      image: 'https://img.ssensemedia.com/images/222259M191004_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/navy-recycled-polyester-cargo-pants/9954251',
    's-text': 'Alexander McQueen',
    's-text 2': 'Navy Recycled Polyester Cargo Pants',
    's-text 3': '$1345',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9954651',
      name: 'Navy Selvedge Shorts',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 590,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/navy-selvedge-shorts/9954651',
      },
      url: '/men/product/alexander-mcqueen/navy-selvedge-shorts/9954651',
      image: 'https://img.ssensemedia.com/images/222259M193002_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/navy-selvedge-shorts/9954651',
    's-text': 'Alexander McQueen',
    's-text 2': 'Navy Selvedge Shorts',
    's-text 3': '$590',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8653001',
      name: 'Gray Nylon Polo',
      brand: {
        '@type': 'Brand',
        name: 'a-cold-wall',
      },
      offers: {
        '@type': 'Offer',
        price: 355,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/a-cold-wall/gray-nylon-polo/8653001',
      },
      url: '/men/product/a-cold-wall/gray-nylon-polo/8653001',
      image: 'https://img.ssensemedia.com/images/221891M212000_1/a-cold-wall-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/a-cold-wall/gray-nylon-polo/8653001',
    's-text': 'A-COLD-WALL*',
    's-text 2': 'Gray Nylon Polo',
    's-text 3': '$355',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9505201',
      name: 'Navy Harness Back Tank Top',
      brand: {
        '@type': 'Brand',
        name: 'dion-lee',
      },
      offers: {
        '@type': 'Offer',
        price: 265,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dion-lee/navy-harness-back-tank-top/9505201',
      },
      url: '/men/product/dion-lee/navy-harness-back-tank-top/9505201',
      image: 'https://img.ssensemedia.com/images/221417M214048_1/dion-lee-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dion-lee/navy-harness-back-tank-top/9505201',
    's-text': 'Dion Lee',
    's-text 2': 'Navy Harness Back Tank Top',
    's-text 3': '$265',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760141',
      name: 'Black Hooded Denim Jacket',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 170,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/black-hooded-denim-jacket/9760141',
      },
      url: '/men/product/dime/black-hooded-denim-jacket/9760141',
      image: 'https://img.ssensemedia.com/images/222841M180006_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/black-hooded-denim-jacket/9760141',
    's-text': 'Dime',
    's-text 2': 'Black Hooded Denim Jacket',
    's-text 3': '$170',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760121',
      name: 'Off-White & Blue Cotton Jacket',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 155,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/off-white-and-blue-cotton-jacket/9760121',
      },
      url: '/men/product/dime/off-white-and-blue-cotton-jacket/9760121',
      image: 'https://img.ssensemedia.com/images/222841M180004_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/off-white-and-blue-cotton-jacket/9760121',
    's-text': 'Dime',
    's-text 2': 'Off-White & Blue Cotton Jacket',
    's-text 3': '$155',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760241',
      name: 'Blue Cotton Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/blue-cotton-hoodie/9760241',
      },
      url: '/men/product/dime/blue-cotton-hoodie/9760241',
      image: 'https://img.ssensemedia.com/images/222841M202012_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/blue-cotton-hoodie/9760241',
    's-text': 'Dime',
    's-text 2': 'Blue Cotton Hoodie',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760251',
      name: 'Gray Cotton Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/gray-cotton-hoodie/9760251',
      },
      url: '/men/product/dime/gray-cotton-hoodie/9760251',
      image: 'https://img.ssensemedia.com/images/222841M202013_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/gray-cotton-hoodie/9760251',
    's-text': 'Dime',
    's-text 2': 'Gray Cotton Hoodie',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760271',
      name: 'Gray Cotton Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/gray-cotton-hoodie/9760271',
      },
      url: '/men/product/dime/gray-cotton-hoodie/9760271',
      image: 'https://img.ssensemedia.com/images/222841M202015_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/gray-cotton-hoodie/9760271',
    's-text': 'Dime',
    's-text 2': 'Gray Cotton Hoodie',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760291',
      name: 'Black BMF Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/black-bmf-hoodie/9760291',
      },
      url: '/men/product/dime/black-bmf-hoodie/9760291',
      image: 'https://img.ssensemedia.com/images/222841M202017_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/black-bmf-hoodie/9760291',
    's-text': 'Dime',
    's-text 2': 'Black BMF Hoodie',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9803881',
      name: 'Gray Cotton Sweatshirt',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 130,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/gray-cotton-sweatshirt/9803881',
      },
      url: '/men/product/dime/gray-cotton-sweatshirt/9803881',
      image: 'https://img.ssensemedia.com/images/222841M204012_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/gray-cotton-sweatshirt/9803881',
    's-text': 'Dime',
    's-text 2': 'Gray Cotton Sweatshirt',
    's-text 3': '$130',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760211',
      name: 'Green Cotton Long Sleeve T-Shirt',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 100,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/green-cotton-long-sleeve-t-shirt/9760211',
      },
      url: '/men/product/dime/green-cotton-long-sleeve-t-shirt/9760211',
      image: 'https://img.ssensemedia.com/images/222841M213018_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/green-cotton-long-sleeve-t-shirt/9760211',
    's-text': 'Dime',
    's-text 2': 'Green Cotton Long Sleeve T-Shirt',
    's-text 3': '$100',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760131',
      name: 'Black Cotton Jacket',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 155,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/black-cotton-jacket/9760131',
      },
      url: '/men/product/dime/black-cotton-jacket/9760131',
      image: 'https://img.ssensemedia.com/images/222841M180005_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/black-cotton-jacket/9760131',
    's-text': 'Dime',
    's-text 2': 'Black Cotton Jacket',
    's-text 3': '$155',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760161',
      name: 'Off-White Cotton Shirt',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/off-white-cotton-shirt/9760161',
      },
      url: '/men/product/dime/off-white-cotton-shirt/9760161',
      image: 'https://img.ssensemedia.com/images/222841M192002_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/off-white-cotton-shirt/9760161',
    's-text': 'Dime',
    's-text 2': 'Off-White Cotton Shirt',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760171',
      name: 'Black Cotton Shirt',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/black-cotton-shirt/9760171',
      },
      url: '/men/product/dime/black-cotton-shirt/9760171',
      image: 'https://img.ssensemedia.com/images/222841M192003_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/black-cotton-shirt/9760171',
    's-text': 'Dime',
    's-text 2': 'Black Cotton Shirt',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760451',
      name: 'Orange Cotton T-Shirt',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 50,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/orange-cotton-t-shirt/9760451',
      },
      url: '/men/product/dime/orange-cotton-t-shirt/9760451',
      image: 'https://img.ssensemedia.com/images/222841M213028_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/orange-cotton-t-shirt/9760451',
    's-text': 'Dime',
    's-text 2': 'Orange Cotton T-Shirt',
    's-text 3': '$50',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760491',
      name: 'Green Cotton Cargo Pants',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/green-cotton-cargo-pants/9760491',
      },
      url: '/men/product/dime/green-cotton-cargo-pants/9760491',
      image: 'https://img.ssensemedia.com/images/222841M188004_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/green-cotton-cargo-pants/9760491',
    's-text': 'Dime',
    's-text 2': 'Green Cotton Cargo Pants',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760561',
      name: 'Black & Gray Polyester Shorts',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 115,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/black-and-gray-polyester-shorts/9760561',
      },
      url: '/men/product/dime/black-and-gray-polyester-shorts/9760561',
      image: 'https://img.ssensemedia.com/images/222841M193005_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/black-and-gray-polyester-shorts/9760561',
    's-text': 'Dime',
    's-text 2': 'Black & Gray Polyester Shorts',
    's-text 3': '$115',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760571',
      name: 'Beige Polyester Shorts',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 115,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/beige-polyester-shorts/9760571',
      },
      url: '/men/product/dime/beige-polyester-shorts/9760571',
      image: 'https://img.ssensemedia.com/images/222841M193006_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/beige-polyester-shorts/9760571',
    's-text': 'Dime',
    's-text 2': 'Beige Polyester Shorts',
    's-text 3': '$115',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760591',
      name: 'Blue Polyester Shorts',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 115,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/blue-polyester-shorts/9760591',
      },
      url: '/men/product/dime/blue-polyester-shorts/9760591',
      image: 'https://img.ssensemedia.com/images/222841M193008_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/blue-polyester-shorts/9760591',
    's-text': 'Dime',
    's-text 2': 'Blue Polyester Shorts',
    's-text 3': '$115',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9760541',
      name: 'Green Cotton Shorts',
      brand: {
        '@type': 'Brand',
        name: 'dime',
      },
      offers: {
        '@type': 'Offer',
        price: 130,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dime/green-cotton-shorts/9760541',
      },
      url: '/men/product/dime/green-cotton-shorts/9760541',
      image: 'https://img.ssensemedia.com/images/222841M193003_1/dime-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dime/green-cotton-shorts/9760541',
    's-text': 'Dime',
    's-text 2': 'Green Cotton Shorts',
    's-text 3': '$130',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8797261',
      name: 'Black Monogram Face Mask',
      brand: {
        '@type': 'Brand',
        name: 'misbhv',
      },
      offers: {
        '@type': 'Offer',
        price: 25,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/misbhv/black-monogram-face-mask/8797261',
      },
      url: '/men/product/misbhv/black-monogram-face-mask/8797261',
      image: 'https://img.ssensemedia.com/images/221937M150001_1/misbhv-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/misbhv/black-monogram-face-mask/8797261',
    's-text': 'MISBHV',
    's-text 2': 'Black Monogram Face Mask',
    's-text 3': '$25',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '6388841',
      name: 'Navy Organic Cotton T-Shirt',
      brand: {
        '@type': 'Brand',
        name: 'camiel-fortgens',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/camiel-fortgens/navy-organic-cotton-t-shirt/6388841',
      },
      url: '/men/product/camiel-fortgens/navy-organic-cotton-t-shirt/6388841',
      image: 'https://img.ssensemedia.com/images/211109M213034_1/camiel-fortgens-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/camiel-fortgens/navy-organic-cotton-t-shirt/6388841',
    's-text': 'Camiel Fortgens',
    's-text 2': 'Navy Organic Cotton T-Shirt',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9396831',
      name: 'Multicolor Denim Bucket Hat',
      brand: {
        '@type': 'Brand',
        name: 'charles-jeffrey-loverboy',
      },
      offers: {
        '@type': 'Offer',
        price: 150,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/charles-jeffrey-loverboy/multicolor-denim-bucket-hat/9396831',
      },
      url: '/men/product/charles-jeffrey-loverboy/multicolor-denim-bucket-hat/9396831',
      image: 'https://img.ssensemedia.com/images/221101M140007_1/charles-jeffrey-loverboy-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/charles-jeffrey-loverboy/multicolor-denim-bucket-hat/9396831',
    's-text': 'Charles Jeffrey Loverboy',
    's-text 2': 'Multicolor Denim Bucket Hat',
    's-text 3': '$150',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9756551',
      name: 'Gray New Jeans',
      brand: {
        '@type': 'Brand',
        name: 'paria-farzaneh',
      },
      offers: {
        '@type': 'Offer',
        price: 575,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/paria-farzaneh/gray-new-jeans/9756551',
      },
      url: '/men/product/paria-farzaneh/gray-new-jeans/9756551',
      image: 'https://img.ssensemedia.com/images/221193M191001_1/paria-farzaneh-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/paria-farzaneh/gray-new-jeans/9756551',
    's-text': 'paria /FARZANEH',
    's-text 2': 'Gray New Jeans',
    's-text 3': '$575',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8405911',
      name: 'Black Chillax Fox Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'maison-kitsune',
      },
      offers: {
        '@type': 'Offer',
        price: 260,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/maison-kitsune/black-chillax-fox-hoodie/8405911',
      },
      url: '/men/product/maison-kitsune/black-chillax-fox-hoodie/8405911',
      image: 'https://img.ssensemedia.com/images/221389M202007_1/maison-kitsune-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/maison-kitsune/black-chillax-fox-hoodie/8405911',
    's-text': 'Maison Kitsuné',
    's-text 2': 'Black Chillax Fox Hoodie',
    's-text 3': '$260',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9044401',
      name: 'SSENSE Exclusive Tan Cotton Polo',
      brand: {
        '@type': 'Brand',
        name: 'le17septembre',
      },
      offers: {
        '@type': 'Offer',
        price: 275,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/le17septembre/ssense-exclusive-tan-cotton-polo/9044401',
      },
      url: '/men/product/le17septembre/ssense-exclusive-tan-cotton-polo/9044401',
      image: 'https://img.ssensemedia.com/images/221495M212000_1/le17septembre-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/le17septembre/ssense-exclusive-tan-cotton-polo/9044401',
    's-text': 'LE17SEPTEMBRE',
    's-text 2': 'SSENSE Exclusive Tan Cotton Polo',
    's-text 3': '$275',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9671951',
      name: 'Black Viscose Cardigan',
      brand: {
        '@type': 'Brand',
        name: 'ludovic-de-saint-sernin',
      },
      offers: {
        '@type': 'Offer',
        price: 550,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ludovic-de-saint-sernin/black-viscose-cardigan/9671951',
      },
      url: '/men/product/ludovic-de-saint-sernin/black-viscose-cardigan/9671951',
      image: 'https://img.ssensemedia.com/images/221388M200001_1/ludovic-de-saint-sernin-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ludovic-de-saint-sernin/black-viscose-cardigan/9671951',
    's-text': 'Ludovic de Saint Sernin',
    's-text 2': 'Black Viscose Cardigan',
    's-text 3': '$550',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9672101',
      name: 'Black Cotton T-Shirt',
      brand: {
        '@type': 'Brand',
        name: 'ludovic-de-saint-sernin',
      },
      offers: {
        '@type': 'Offer',
        price: 235,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ludovic-de-saint-sernin/black-cotton-t-shirt/9672101',
      },
      url: '/men/product/ludovic-de-saint-sernin/black-cotton-t-shirt/9672101',
      image: 'https://img.ssensemedia.com/images/221388M213013_1/ludovic-de-saint-sernin-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ludovic-de-saint-sernin/black-cotton-t-shirt/9672101',
    's-text': 'Ludovic de Saint Sernin',
    's-text 2': 'Black Cotton T-Shirt',
    's-text 3': '$235',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9107121',
      name: 'Taupe Typo Vest',
      brand: {
        '@type': 'Brand',
        name: 'mfpen',
      },
      offers: {
        '@type': 'Offer',
        price: 220,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/mfpen/taupe-typo-vest/9107121',
      },
      url: '/men/product/mfpen/taupe-typo-vest/9107121',
      image: 'https://img.ssensemedia.com/images/221505M185001_1/mfpen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/mfpen/taupe-typo-vest/9107121',
    's-text': 'mfpen',
    's-text 2': 'Taupe Typo Vest',
    's-text 3': '$220',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9846921',
      name: 'Gray Item Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'apc',
      },
      offers: {
        '@type': 'Offer',
        price: 215,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/apc/gray-item-hoodie/9846921',
      },
      url: '/men/product/apc/gray-item-hoodie/9846921',
      image: 'https://img.ssensemedia.com/images/222252M213118_1/apc-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/apc/gray-item-hoodie/9846921',
    's-text': 'A.P.C.',
    's-text 2': 'Gray Item Hoodie',
    's-text 3': '$215',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9846911',
      name: 'Black Item Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'apc',
      },
      offers: {
        '@type': 'Offer',
        price: 215,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/apc/black-item-hoodie/9846911',
      },
      url: '/men/product/apc/black-item-hoodie/9846911',
      image: 'https://img.ssensemedia.com/images/222252M213117_1/apc-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/apc/black-item-hoodie/9846911',
    's-text': 'A.P.C.',
    's-text 2': 'Black Item Hoodie',
    's-text 3': '$215',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9846901',
      name: 'Navy Item Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'apc',
      },
      offers: {
        '@type': 'Offer',
        price: 215,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/apc/navy-item-hoodie/9846901',
      },
      url: '/men/product/apc/navy-item-hoodie/9846901',
      image: 'https://img.ssensemedia.com/images/222252M213116_1/apc-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/apc/navy-item-hoodie/9846901',
    's-text': 'A.P.C.',
    's-text 2': 'Navy Item Hoodie',
    's-text 3': '$215',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9847131',
      name: 'Gray Item Shorts',
      brand: {
        '@type': 'Brand',
        name: 'apc',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/apc/gray-item-shorts/9847131',
      },
      url: '/men/product/apc/gray-item-shorts/9847131',
      image: 'https://img.ssensemedia.com/images/222252M213139_1/apc-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/apc/gray-item-shorts/9847131',
    's-text': 'A.P.C.',
    's-text 2': 'Gray Item Shorts',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9847141',
      name: 'Black Item Shorts',
      brand: {
        '@type': 'Brand',
        name: 'apc',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/apc/black-item-shorts/9847141',
      },
      url: '/men/product/apc/black-item-shorts/9847141',
      image: 'https://img.ssensemedia.com/images/222252M213140_1/apc-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/apc/black-item-shorts/9847141',
    's-text': 'A.P.C.',
    's-text 2': 'Black Item Shorts',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9847151',
      name: 'Navy Item Shorts',
      brand: {
        '@type': 'Brand',
        name: 'apc',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/apc/navy-item-shorts/9847151',
      },
      url: '/men/product/apc/navy-item-shorts/9847151',
      image: 'https://img.ssensemedia.com/images/222252M213141_1/apc-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/apc/navy-item-shorts/9847151',
    's-text': 'A.P.C.',
    's-text 2': 'Navy Item Shorts',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9899881',
      name: 'Blue Oh G Denim Jacket',
      brand: {
        '@type': 'Brand',
        name: 'ksubi',
      },
      offers: {
        '@type': 'Offer',
        price: 210,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ksubi/blue-oh-g-denim-jacket/9899881',
      },
      url: '/men/product/ksubi/blue-oh-g-denim-jacket/9899881',
      image: 'https://img.ssensemedia.com/images/222088M177003_1/ksubi-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ksubi/blue-oh-g-denim-jacket/9899881',
    's-text': 'Ksubi',
    's-text 2': 'Blue Oh G Denim Jacket',
    's-text 3': '$210',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9896881',
      name: 'Navy Plus Antidote Jacket',
      brand: {
        '@type': 'Brand',
        name: 'ksubi',
      },
      offers: {
        '@type': 'Offer',
        price: 195,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ksubi/navy-plus-antidote-jacket/9896881',
      },
      url: '/men/product/ksubi/navy-plus-antidote-jacket/9896881',
      image: 'https://img.ssensemedia.com/images/222088M202002_1/ksubi-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ksubi/navy-plus-antidote-jacket/9896881',
    's-text': 'Ksubi',
    's-text 2': 'Navy Plus Antidote Jacket',
    's-text 3': '$195',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9896771',
      name: 'Red Devil Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'ksubi',
      },
      offers: {
        '@type': 'Offer',
        price: 195,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ksubi/red-devil-hoodie/9896771',
      },
      url: '/men/product/ksubi/red-devil-hoodie/9896771',
      image: 'https://img.ssensemedia.com/images/222088M202001_1/ksubi-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ksubi/red-devil-hoodie/9896771',
    's-text': 'Ksubi',
    's-text 2': 'Red Devil Hoodie',
    's-text 3': '$195',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9896951',
      name: 'Gray Cotton Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'ksubi',
      },
      offers: {
        '@type': 'Offer',
        price: 180,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ksubi/gray-cotton-hoodie/9896951',
      },
      url: '/men/product/ksubi/gray-cotton-hoodie/9896951',
      image: 'https://img.ssensemedia.com/images/222088M202004_1/ksubi-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ksubi/gray-cotton-hoodie/9896951',
    's-text': 'Ksubi',
    's-text 2': 'Gray Cotton Hoodie',
    's-text 3': '$180',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9899961',
      name: 'Beige 4 X 4 Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'ksubi',
      },
      offers: {
        '@type': 'Offer',
        price: 180,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/ksubi/beige-4-x-4-hoodie/9899961',
      },
      url: '/men/product/ksubi/beige-4-x-4-hoodie/9899961',
      image: 'https://img.ssensemedia.com/images/222088M202023_1/ksubi-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/ksubi/beige-4-x-4-hoodie/9899961',
    's-text': 'Ksubi',
    's-text 2': 'Beige 4 X 4 Hoodie',
    's-text 3': '$180',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9532021',
      name: 'SSENSE Exclusive Farm Shorts',
      brand: {
        '@type': 'Brand',
        name: 'collina-strada',
      },
      offers: {
        '@type': 'Offer',
        price: 400,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/collina-strada/ssense-exclusive-farm-shorts/9532021',
      },
      url: '/men/product/collina-strada/ssense-exclusive-farm-shorts/9532021',
      image: 'https://img.ssensemedia.com/images/221236M193007_1/collina-strada-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/collina-strada/ssense-exclusive-farm-shorts/9532021',
    's-text': 'Collina Strada',
    's-text 2': 'SSENSE Exclusive Farm Shorts',
    's-text 3': '$400',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9956991',
      name: 'Green Cotton Cargo Pants',
      brand: {
        '@type': 'Brand',
        name: 'frame',
      },
      offers: {
        '@type': 'Offer',
        price: 325,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/frame/green-cotton-cargo-pants/9956991',
      },
      url: '/men/product/frame/green-cotton-cargo-pants/9956991',
      image: 'https://img.ssensemedia.com/images/222455M188000_1/frame-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/frame/green-cotton-cargo-pants/9956991',
    's-text': 'FRAME',
    's-text 2': 'Green Cotton Cargo Pants',
    's-text 3': '$325',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9957511',
      name: 'Blue Denim Shorts',
      brand: {
        '@type': 'Brand',
        name: 'frame',
      },
      offers: {
        '@type': 'Offer',
        price: 325,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/frame/blue-denim-shorts/9957511',
      },
      url: '/men/product/frame/blue-denim-shorts/9957511',
      image: 'https://img.ssensemedia.com/images/222455M193007_1/frame-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/frame/blue-denim-shorts/9957511',
    's-text': 'FRAME',
    's-text 2': 'Blue Denim Shorts',
    's-text 3': '$325',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9266861',
      name: 'Beige Cotton Cargo Trousers',
      brand: {
        '@type': 'Brand',
        name: 'izzue',
      },
      offers: {
        '@type': 'Offer',
        price: 85,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/izzue/beige-cotton-cargo-trousers/9266861',
      },
      url: '/men/product/izzue/beige-cotton-cargo-trousers/9266861',
      image: 'https://img.ssensemedia.com/images/221284M188003_1/izzue-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/izzue/beige-cotton-cargo-trousers/9266861',
    's-text': 'Izzue',
    's-text 2': 'Beige Cotton Cargo Trousers',
    's-text 3': '$85',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9266331',
      name: 'Green Cotton Trousers',
      brand: {
        '@type': 'Brand',
        name: 'izzue',
      },
      offers: {
        '@type': 'Offer',
        price: 95,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/izzue/green-cotton-trousers/9266331',
      },
      url: '/men/product/izzue/green-cotton-trousers/9266331',
      image: 'https://img.ssensemedia.com/images/221284M191000_1/izzue-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/izzue/green-cotton-trousers/9266331',
    's-text': 'Izzue',
    's-text 2': 'Green Cotton Trousers',
    's-text 3': '$95',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8738101',
      name: 'Brown Polyester Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'jieda',
      },
      offers: {
        '@type': 'Offer',
        price: 390,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/jieda/brown-polyester-hoodie/8738101',
      },
      url: '/men/product/jieda/brown-polyester-hoodie/8738101',
      image: 'https://img.ssensemedia.com/images/221819M202000_1/jieda-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/jieda/brown-polyester-hoodie/8738101',
    's-text': 'JieDa',
    's-text 2': 'Brown Polyester Hoodie',
    's-text 3': '$390',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9601161',
      name: 'Brown Puff Trousers',
      brand: {
        '@type': 'Brand',
        name: 'notsonormal',
      },
      offers: {
        '@type': 'Offer',
        price: 370,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/notsonormal/brown-puff-trousers/9601161',
      },
      url: '/men/product/notsonormal/brown-puff-trousers/9601161',
      image: 'https://img.ssensemedia.com/images/221438M190001_1/notsonormal-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/notsonormal/brown-puff-trousers/9601161',
    's-text': 'NotSoNormal',
    's-text 2': 'Brown Puff Trousers',
    's-text 3': '$370',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9227421',
      name: 'Pink Prepster Shorts',
      brand: {
        '@type': 'Brand',
        name: 'polo-ralph-lauren',
      },
      offers: {
        '@type': 'Offer',
        price: 80,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/polo-ralph-lauren/pink-prepster-shorts/9227421',
      },
      url: '/men/product/polo-ralph-lauren/pink-prepster-shorts/9227421',
      image: 'https://img.ssensemedia.com/images/221213M191009_1/polo-ralph-lauren-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/polo-ralph-lauren/pink-prepster-shorts/9227421',
    's-text': 'Polo Ralph Lauren',
    's-text 2': 'Pink Prepster Shorts',
    's-text 3': '$80',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9799231',
      name: 'Beige Cotton Hoodie',
      brand: {
        '@type': 'Brand',
        name: 'theory',
      },
      offers: {
        '@type': 'Offer',
        price: 270,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/theory/beige-cotton-hoodie/9799231',
      },
      url: '/men/product/theory/beige-cotton-hoodie/9799231',
      image: 'https://img.ssensemedia.com/images/222216M202002_1/theory-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/theory/beige-cotton-hoodie/9799231',
    's-text': 'Theory',
    's-text 2': 'Beige Cotton Hoodie',
    's-text 3': '$270',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9800561',
      name: 'Gray Goris Polo',
      brand: {
        '@type': 'Brand',
        name: 'theory',
      },
      offers: {
        '@type': 'Offer',
        price: 190,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/theory/gray-goris-polo/9800561',
      },
      url: '/men/product/theory/gray-goris-polo/9800561',
      image: 'https://img.ssensemedia.com/images/222216M212019_1/theory-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/theory/gray-goris-polo/9800561',
    's-text': 'Theory',
    's-text 2': 'Gray Goris Polo',
    's-text 3': '$190',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9880331',
      name: 'Navy Dylan Trousers',
      brand: {
        '@type': 'Brand',
        name: 'vince',
      },
      offers: {
        '@type': 'Offer',
        price: 295,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/vince/navy-dylan-trousers/9880331',
      },
      url: '/men/product/vince/navy-dylan-trousers/9880331',
      image: 'https://img.ssensemedia.com/images/222875M191006_1/vince-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/vince/navy-dylan-trousers/9880331',
    's-text': 'Vince',
    's-text 2': 'Navy Dylan Trousers',
    's-text 3': '$295',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9824431',
      name: 'Off-White Ivan Denim Jacket',
      brand: {
        '@type': 'Brand',
        name: 'wood-wood',
      },
      offers: {
        '@type': 'Offer',
        price: 250,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/wood-wood/off-white-ivan-denim-jacket/9824431',
      },
      url: '/men/product/wood-wood/off-white-ivan-denim-jacket/9824431',
      image: 'https://img.ssensemedia.com/images/222378M177000_1/wood-wood-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/wood-wood/off-white-ivan-denim-jacket/9824431',
    's-text': 'Wood Wood',
    's-text 2': 'Off-White Ivan Denim Jacket',
    's-text 3': '$250',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8955931',
      name: 'Off-White Cotton Shorts',
      brand: {
        '@type': 'Brand',
        name: 'y-3',
      },
      offers: {
        '@type': 'Offer',
        price: 180,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/y-3/off-white-cotton-shorts/8955931',
      },
      url: '/men/product/y-3/off-white-cotton-shorts/8955931',
      image: 'https://img.ssensemedia.com/images/221138M193014_1/y-3-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/y-3/off-white-cotton-shorts/8955931',
    's-text': 'Y-3',
    's-text 2': 'Off-White Cotton Shorts',
    's-text 3': '$180',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '7758721',
      name: 'Black Gabardine Logo Cap',
      brand: {
        '@type': 'Brand',
        name: 'dsquared2',
      },
      offers: {
        '@type': 'Offer',
        price: 150,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/dsquared2/black-gabardine-logo-cap/7758721',
      },
      url: '/men/product/dsquared2/black-gabardine-logo-cap/7758721',
      image: 'https://img.ssensemedia.com/images/212148M139265_1/dsquared2-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/dsquared2/black-gabardine-logo-cap/7758721',
    's-text': 'Dsquared2',
    's-text 2': 'Black Gabardine Logo Cap',
    's-text 3': '$150',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9776131',
      name: 'Black Cotton Sweatshirt',
      brand: {
        '@type': 'Brand',
        name: 'hugo-hugo-boss',
      },
      offers: {
        '@type': 'Offer',
        price: 105,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/hugo-hugo-boss/black-cotton-sweatshirt/9776131',
      },
      url: '/men/product/hugo-hugo-boss/black-cotton-sweatshirt/9776131',
      image: 'https://img.ssensemedia.com/images/222084M204003_1/hugo-hugo-boss-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/hugo-hugo-boss/black-cotton-sweatshirt/9776131',
    's-text': 'Hugo',
    's-text 2': 'Black Cotton Sweatshirt',
    's-text 3': '$105',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9788191',
      name: 'Blue & White Cotton Shirt',
      brand: {
        '@type': 'Brand',
        name: 'hugo-hugo-boss',
      },
      offers: {
        '@type': 'Offer',
        price: 125,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/hugo-hugo-boss/blue-and-white-cotton-shirt/9788191',
      },
      url: '/men/product/hugo-hugo-boss/blue-and-white-cotton-shirt/9788191',
      image: 'https://img.ssensemedia.com/images/222084M192006_1/hugo-hugo-boss-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/hugo-hugo-boss/blue-and-white-cotton-shirt/9788191',
    's-text': 'Hugo',
    's-text 2': 'Blue & White Cotton Shirt',
    's-text 3': '$125',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10001751',
      name: 'Blue Graffiti Metropolitan Backpack',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 925,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/blue-graffiti-metropolitan-backpack/10001751',
      },
      url: '/men/product/alexander-mcqueen/blue-graffiti-metropolitan-backpack/10001751',
      image: 'https://img.ssensemedia.com/images/222259M166003_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/blue-graffiti-metropolitan-backpack/10001751',
    's-text': 'Alexander McQueen',
    's-text 2': 'Blue Graffiti Metropolitan Backpack',
    's-text 3': '$925',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9137221',
      name: 'Black Small Rubber Buffer Messenger Bag',
      brand: {
        '@type': 'Brand',
        name: 'bottega-veneta',
      },
      offers: {
        '@type': 'Offer',
        price: 1230,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/bottega-veneta/black-small-rubber-buffer-messenger-bag/9137221',
      },
      url: '/men/product/bottega-veneta/black-small-rubber-buffer-messenger-bag/9137221',
      image: 'https://img.ssensemedia.com/images/221798M170090_1/bottega-veneta-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/bottega-veneta/black-small-rubber-buffer-messenger-bag/9137221',
    's-text': 'Bottega Veneta',
    's-text 2': 'Black Small Rubber Buffer Messenger Bag',
    's-text 3': '$1230',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9829041',
      name: 'Green Organizer Pouch',
      brand: {
        '@type': 'Brand',
        name: 'bottega-veneta',
      },
      offers: {
        '@type': 'Offer',
        price: 1590,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/bottega-veneta/green-organizer-pouch/9829041',
      },
      url: '/men/product/bottega-veneta/green-organizer-pouch/9829041',
      image: 'https://img.ssensemedia.com/images/221798M171570_1/bottega-veneta-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/bottega-veneta/green-organizer-pouch/9829041',
    's-text': 'Bottega Veneta',
    's-text 2': 'Green Organizer Pouch',
    's-text 3': '$1590',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9581831',
      name: 'Black Faux-Leather Pouch',
      brand: {
        '@type': 'Brand',
        name: 'situationist',
      },
      offers: {
        '@type': 'Offer',
        price: 215,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/situationist/black-faux-leather-pouch/9581831',
      },
      url: '/men/product/situationist/black-faux-leather-pouch/9581831',
      image: 'https://img.ssensemedia.com/images/221149M171032_1/situationist-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/situationist/black-faux-leather-pouch/9581831',
    's-text': 'Situationist',
    's-text 2': 'Black Faux-Leather Pouch',
    's-text 3': '$215',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955231',
      name: 'Black Demanta Tote',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1185,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-demanta-tote/9955231',
      },
      url: '/men/product/alexander-mcqueen/black-demanta-tote/9955231',
      image: 'https://img.ssensemedia.com/images/222259M172001_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-demanta-tote/9955231',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Demanta Tote',
    's-text 3': '$1185',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955211',
      name: 'Black Skull Tote',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1075,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-skull-tote/9955211',
      },
      url: '/men/product/alexander-mcqueen/black-skull-tote/9955211',
      image: 'https://img.ssensemedia.com/images/222259M172000_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-skull-tote/9955211',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Skull Tote',
    's-text 3': '$1075',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955871',
      name: 'Black Punk Stud Derbys',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1345,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-punk-stud-derbys/9955871',
      },
      url: '/men/product/alexander-mcqueen/black-punk-stud-derbys/9955871',
      image: 'https://img.ssensemedia.com/images/222259M225000_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-punk-stud-derbys/9955871',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Punk Stud Derbys',
    's-text 3': '$1345',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955881',
      name: 'Black Stud Loafers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1580,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-stud-loafers/9955881',
      },
      url: '/men/product/alexander-mcqueen/black-stud-loafers/9955881',
      image: 'https://img.ssensemedia.com/images/222259M231000_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-stud-loafers/9955881',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Stud Loafers',
    's-text 3': '$1580',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8522081',
      name: 'Black Embroidered Greca Loafers',
      brand: {
        '@type': 'Brand',
        name: 'versace',
      },
      offers: {
        '@type': 'Offer',
        price: 815,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/versace/black-embroidered-greca-loafers/8522081',
      },
      url: '/men/product/versace/black-embroidered-greca-loafers/8522081',
      image: 'https://img.ssensemedia.com/images/221404M231004_1/versace-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/versace/black-embroidered-greca-loafers/8522081',
    's-text': 'Versace',
    's-text 2': 'Black Embroidered Greca Loafers',
    's-text 3': '$815',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955741',
      name: 'Blue Pool Slide Sandals',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 340,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/blue-pool-slide-sandals/9955741',
      },
      url: '/men/product/alexander-mcqueen/blue-pool-slide-sandals/9955741',
      image: 'https://img.ssensemedia.com/images/222259M234000_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/blue-pool-slide-sandals/9955741',
    's-text': 'Alexander McQueen',
    's-text 2': 'Blue Pool Slide Sandals',
    's-text 3': '$340',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955911',
      name: 'Gray Graffiti Tread Slick High-Top Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1060,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/gray-graffiti-tread-slick-high-top-sneakers/9955911',
      },
      url: '/men/product/alexander-mcqueen/gray-graffiti-tread-slick-high-top-sneakers/9955911',
      image: 'https://img.ssensemedia.com/images/222259M236005_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/gray-graffiti-tread-slick-high-top-sneakers/9955911',
    's-text': 'Alexander McQueen',
    's-text 2': 'Gray Graffiti Tread Slick High-Top Sneakers',
    's-text 3': '$1060',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955731',
      name: 'White Tread Slick Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 775,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-tread-slick-sneakers/9955731',
      },
      url: '/men/product/alexander-mcqueen/white-tread-slick-sneakers/9955731',
      image: 'https://img.ssensemedia.com/images/222259M237006_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-tread-slick-sneakers/9955731',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Tread Slick Sneakers',
    's-text 3': '$775',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955781',
      name: 'White Oversized Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 635,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-oversized-sneakers/9955781',
      },
      url: '/men/product/alexander-mcqueen/white-oversized-sneakers/9955781',
      image: 'https://img.ssensemedia.com/images/222259M237010_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-oversized-sneakers/9955781',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Oversized Sneakers',
    's-text 3': '$635',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955841',
      name: 'Silver Oversized Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 2105,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/silver-oversized-sneakers/9955841',
      },
      url: '/men/product/alexander-mcqueen/silver-oversized-sneakers/9955841',
      image: 'https://img.ssensemedia.com/images/222259M237013_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/silver-oversized-sneakers/9955841',
    's-text': 'Alexander McQueen',
    's-text 2': 'Silver Oversized Sneakers',
    's-text 3': '$2105',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9955861',
      name: 'Black Punk Stud Lace-Up Boots',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 1560,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-punk-stud-lace-up-boots/9955861',
      },
      url: '/men/product/alexander-mcqueen/black-punk-stud-lace-up-boots/9955861',
      image: 'https://img.ssensemedia.com/images/222259M255001_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-punk-stud-lace-up-boots/9955861',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Punk Stud Lace-Up Boots',
    's-text 3': '$1560',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10037831',
      name: 'Gray Court Trainer Mid-Top Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 880,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/gray-court-trainer-mid-top-sneakers/10037831',
      },
      url: '/men/product/alexander-mcqueen/gray-court-trainer-mid-top-sneakers/10037831',
      image: 'https://img.ssensemedia.com/images/222259M237044_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/gray-court-trainer-mid-top-sneakers/10037831',
    's-text': 'Alexander McQueen',
    's-text 2': 'Gray Court Trainer Mid-Top Sneakers',
    's-text 3': '$880',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10037871',
      name: 'Black Oversized Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 820,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-oversized-sneakers/10037871',
      },
      url: '/men/product/alexander-mcqueen/black-oversized-sneakers/10037871',
      image: 'https://img.ssensemedia.com/images/222259M237048_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-oversized-sneakers/10037871',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Oversized Sneakers',
    's-text 3': '$820',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10037851',
      name: 'White Deck Plimsoll Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 705,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/white-deck-plimsoll-sneakers/10037851',
      },
      url: '/men/product/alexander-mcqueen/white-deck-plimsoll-sneakers/10037851',
      image: 'https://img.ssensemedia.com/images/222259M237046_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/white-deck-plimsoll-sneakers/10037851',
    's-text': 'Alexander McQueen',
    's-text 2': 'White Deck Plimsoll Sneakers',
    's-text 3': '$705',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8636901',
      name: 'Off-White Halo Low-Top Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'eytys',
      },
      offers: {
        '@type': 'Offer',
        price: 455,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/eytys/off-white-halo-low-top-sneakers/8636901',
      },
      url: '/men/product/eytys/off-white-halo-low-top-sneakers/8636901',
      image: 'https://img.ssensemedia.com/images/221640M237015_1/eytys-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/eytys/off-white-halo-low-top-sneakers/8636901',
    's-text': 'Eytys',
    's-text 2': 'Off-White Halo Low-Top Sneakers',
    's-text 3': '$455',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '8540741',
      name: 'Black XA-Pro 3D Low-Top Sneakers',
      brand: {
        '@type': 'Brand',
        name: 'salomon',
      },
      offers: {
        '@type': 'Offer',
        price: 180,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/salomon/black-xa-pro-3d-low-top-sneakers/8540741',
      },
      url: '/men/product/salomon/black-xa-pro-3d-low-top-sneakers/8540741',
      image: 'https://img.ssensemedia.com/images/221837M237015_1/salomon-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/salomon/black-xa-pro-3d-low-top-sneakers/8540741',
    's-text': 'Salomon',
    's-text 2': 'Black XA-Pro 3D Low-Top Sneakers',
    's-text 3': '$180',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9169651',
      name: 'Brown Sport Sandals',
      brand: {
        '@type': 'Brand',
        name: 'coach-1941',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/coach-1941/brown-sport-sandals/9169651',
      },
      url: '/men/product/coach-1941/brown-sport-sandals/9169651',
      image: 'https://img.ssensemedia.com/images/221903M237045_1/coach-1941-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/coach-1941/brown-sport-sandals/9169651',
    's-text': 'Coach 1941',
    's-text 2': 'Brown Sport Sandals',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9169661',
      name: 'Navy Sport Sandals',
      brand: {
        '@type': 'Brand',
        name: 'coach-1941',
      },
      offers: {
        '@type': 'Offer',
        price: 165,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/coach-1941/navy-sport-sandals/9169661',
      },
      url: '/men/product/coach-1941/navy-sport-sandals/9169661',
      image: 'https://img.ssensemedia.com/images/221903M237046_1/coach-1941-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/coach-1941/navy-sport-sandals/9169661',
    's-text': 'Coach 1941',
    's-text 2': 'Navy Sport Sandals',
    's-text 3': '$165',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9087661',
      name: 'Black Suede Coal Desert Boots',
      brand: {
        '@type': 'Brand',
        name: 'clarks-originals',
      },
      offers: {
        '@type': 'Offer',
        price: 205,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/clarks-originals/black-suede-coal-desert-boots/9087661',
      },
      url: '/men/product/clarks-originals/black-suede-coal-desert-boots/9087661',
      image: 'https://img.ssensemedia.com/images/221094M224010_1/clarks-originals-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/clarks-originals/black-suede-coal-desert-boots/9087661',
    's-text': 'Clarks Originals',
    's-text 2': 'Black Suede Coal Desert Boots',
    's-text 3': '$205',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9087691',
      name: 'Black Suede Desert Trek Gore-Tex Lace-Up Shoes',
      brand: {
        '@type': 'Brand',
        name: 'clarks-originals',
      },
      offers: {
        '@type': 'Offer',
        price: 205,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/clarks-originals/black-suede-desert-trek-gore-tex-lace-up-shoes/9087691',
      },
      url: '/men/product/clarks-originals/black-suede-desert-trek-gore-tex-lace-up-shoes/9087691',
      image: 'https://img.ssensemedia.com/images/221094M225018_1/clarks-originals-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/clarks-originals/black-suede-desert-trek-gore-tex-lace-up-shoes/9087691',
    's-text': 'Clarks Originals',
    's-text 2': 'Black Suede Desert Trek Gore-Tex Lace-Up Shoes',
    's-text 3': '$205',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10116401',
      name: 'Silver Alto Necklace',
      brand: {
        '@type': 'Brand',
        name: 'isabel-marant',
      },
      offers: {
        '@type': 'Offer',
        price: 175,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/isabel-marant/silver-alto-necklace/10116401',
      },
      url: '/men/product/isabel-marant/silver-alto-necklace/10116401',
      image: 'https://img.ssensemedia.com/images/222600M145097_1/isabel-marant-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/isabel-marant/silver-alto-necklace/10116401',
    's-text': 'Isabel Marant',
    's-text 2': 'Silver Alto Necklace',
    's-text 3': '$175',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411651',
      name: 'Silver #8551 Necklace',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 120,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-8551-necklace/10411651',
      },
      url: '/men/product/numbering/silver-8551-necklace/10411651',
      image: 'https://img.ssensemedia.com/images/222439M145001_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-8551-necklace/10411651',
    's-text': 'Numbering',
    's-text 2': 'Silver #8551 Necklace',
    's-text 3': '$120',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9712481',
      name: 'Gold Bold Ball Chain Choker',
      brand: {
        '@type': 'Brand',
        name: 'in-gold-we-trust',
      },
      offers: {
        '@type': 'Offer',
        price: 235,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/in-gold-we-trust/gold-bold-ball-chain-choker/9712481',
      },
      url: '/men/product/in-gold-we-trust/gold-bold-ball-chain-choker/9712481',
      image: 'https://img.ssensemedia.com/images/221490M145052_1/in-gold-we-trust-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/in-gold-we-trust/gold-bold-ball-chain-choker/9712481',
    's-text': 'IN GOLD WE TRUST PARIS',
    's-text 2': 'Gold Bold Ball Chain Choker',
    's-text 3': '$235',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9697191',
      name: 'SSENSE Exclusive Gold USB-C Necklace',
      brand: {
        '@type': 'Brand',
        name: 'in-gold-we-trust',
      },
      offers: {
        '@type': 'Offer',
        price: 265,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/in-gold-we-trust/ssense-exclusive-gold-usb-c-necklace/9697191',
      },
      url: '/men/product/in-gold-we-trust/ssense-exclusive-gold-usb-c-necklace/9697191',
      image: 'https://img.ssensemedia.com/images/221490M145013_1/in-gold-we-trust-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/in-gold-we-trust/ssense-exclusive-gold-usb-c-necklace/9697191',
    's-text': 'IN GOLD WE TRUST PARIS',
    's-text 2': 'SSENSE Exclusive Gold USB-C Necklace',
    's-text 3': '$265',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9697201',
      name: 'SSENSE Exclusive Silver USB Necklace',
      brand: {
        '@type': 'Brand',
        name: 'in-gold-we-trust',
      },
      offers: {
        '@type': 'Offer',
        price: 300,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/in-gold-we-trust/ssense-exclusive-silver-usb-necklace/9697201',
      },
      url: '/men/product/in-gold-we-trust/ssense-exclusive-silver-usb-necklace/9697201',
      image: 'https://img.ssensemedia.com/images/221490M145014_1/in-gold-we-trust-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/in-gold-we-trust/ssense-exclusive-silver-usb-necklace/9697201',
    's-text': 'IN GOLD WE TRUST PARIS',
    's-text 2': 'SSENSE Exclusive Silver USB Necklace',
    's-text 3': '$300',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9697211',
      name: 'SSENSE Exclusive Gold USB Necklace',
      brand: {
        '@type': 'Brand',
        name: 'in-gold-we-trust',
      },
      offers: {
        '@type': 'Offer',
        price: 300,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/in-gold-we-trust/ssense-exclusive-gold-usb-necklace/9697211',
      },
      url: '/men/product/in-gold-we-trust/ssense-exclusive-gold-usb-necklace/9697211',
      image: 'https://img.ssensemedia.com/images/221490M145015_1/in-gold-we-trust-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/in-gold-we-trust/ssense-exclusive-gold-usb-necklace/9697211',
    's-text': 'IN GOLD WE TRUST PARIS',
    's-text 2': 'SSENSE Exclusive Gold USB Necklace',
    's-text 3': '$300',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411711',
      name: 'SSENSE Exclusive Silver #5702 Necklace',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 225,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/ssense-exclusive-silver-5702-necklace/10411711',
      },
      url: '/men/product/numbering/ssense-exclusive-silver-5702-necklace/10411711',
      image: 'https://img.ssensemedia.com/images/222439M145005_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/ssense-exclusive-silver-5702-necklace/10411711',
    's-text': 'Numbering',
    's-text 2': 'SSENSE Exclusive Silver #5702 Necklace',
    's-text 3': '$225',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411721',
      name: 'SSENSE Exclusive Gold #5702 Necklace',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 225,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/ssense-exclusive-gold-5702-necklace/10411721',
      },
      url: '/men/product/numbering/ssense-exclusive-gold-5702-necklace/10411721',
      image: 'https://img.ssensemedia.com/images/222439M145006_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/ssense-exclusive-gold-5702-necklace/10411721',
    's-text': 'Numbering',
    's-text 2': 'SSENSE Exclusive Gold #5702 Necklace',
    's-text 3': '$225',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '9712521',
      name: 'Silver Cuban Chain Choker',
      brand: {
        '@type': 'Brand',
        name: 'in-gold-we-trust',
      },
      offers: {
        '@type': 'Offer',
        price: 330,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/in-gold-we-trust/silver-cuban-chain-choker/9712521',
      },
      url: '/men/product/in-gold-we-trust/silver-cuban-chain-choker/9712521',
      image: 'https://img.ssensemedia.com/images/221490M145056_1/in-gold-we-trust-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/in-gold-we-trust/silver-cuban-chain-choker/9712521',
    's-text': 'IN GOLD WE TRUST PARIS',
    's-text 2': 'Silver Cuban Chain Choker',
    's-text 3': '$330',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10001381',
      name: 'Black Cord Skull Bracelet',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 210,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-cord-skull-bracelet/10001381',
      },
      url: '/men/product/alexander-mcqueen/black-cord-skull-bracelet/10001381',
      image: 'https://img.ssensemedia.com/images/222259M142015_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-cord-skull-bracelet/10001381',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Cord Skull Bracelet',
    's-text 3': '$210',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10001391',
      name: 'Black Cord Skull Bracelet',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 210,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/black-cord-skull-bracelet/10001391',
      },
      url: '/men/product/alexander-mcqueen/black-cord-skull-bracelet/10001391',
      image: 'https://img.ssensemedia.com/images/222259M142016_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/black-cord-skull-bracelet/10001391',
    's-text': 'Alexander McQueen',
    's-text 2': 'Black Cord Skull Bracelet',
    's-text 3': '$210',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10413091',
      name: 'Silver #3915 Bracelet',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 275,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-3915-bracelet/10413091',
      },
      url: '/men/product/numbering/silver-3915-bracelet/10413091',
      image: 'https://img.ssensemedia.com/images/222439M142004_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-3915-bracelet/10413091',
    's-text': 'Numbering',
    's-text 2': 'Silver #3915 Bracelet',
    's-text 3': '$275',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10116441',
      name: 'Silver Color Stripe Bracelet',
      brand: {
        '@type': 'Brand',
        name: 'isabel-marant',
      },
      offers: {
        '@type': 'Offer',
        price: 110,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/isabel-marant/silver-color-stripe-bracelet/10116441',
      },
      url: '/men/product/isabel-marant/silver-color-stripe-bracelet/10116441',
      image: 'https://img.ssensemedia.com/images/222600M142093_1/isabel-marant-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/isabel-marant/silver-color-stripe-bracelet/10116441',
    's-text': 'Isabel Marant',
    's-text 2': 'Silver Color Stripe Bracelet',
    's-text 3': '$110',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10116451',
      name: 'Silver Color Stripe Bracelet',
      brand: {
        '@type': 'Brand',
        name: 'isabel-marant',
      },
      offers: {
        '@type': 'Offer',
        price: 110,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/isabel-marant/silver-color-stripe-bracelet/10116451',
      },
      url: '/men/product/isabel-marant/silver-color-stripe-bracelet/10116451',
      image: 'https://img.ssensemedia.com/images/222600M142094_1/isabel-marant-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/isabel-marant/silver-color-stripe-bracelet/10116451',
    's-text': 'Isabel Marant',
    's-text 2': 'Silver Color Stripe Bracelet',
    's-text 3': '$110',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411631',
      name: 'Silver #1741 Earring',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 115,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-1741-earring/10411631',
      },
      url: '/men/product/numbering/silver-1741-earring/10411631',
      image: 'https://img.ssensemedia.com/images/222439M144002_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-1741-earring/10411631',
    's-text': 'Numbering',
    's-text 2': 'Silver #1741 Earring',
    's-text 3': '$115',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411611',
      name: 'Silver #1904 Earring',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 55,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-1904-earring/10411611',
      },
      url: '/men/product/numbering/silver-1904-earring/10411611',
      image: 'https://img.ssensemedia.com/images/222439M144000_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-1904-earring/10411611',
    's-text': 'Numbering',
    's-text 2': 'Silver #1904 Earring',
    's-text 3': '$55',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411761',
      name: 'SSENSE Exclusive Silver #3108 Hoop Earring',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/ssense-exclusive-silver-3108-hoop-earring/10411761',
      },
      url: '/men/product/numbering/ssense-exclusive-silver-3108-hoop-earring/10411761',
      image: 'https://img.ssensemedia.com/images/222439M144004_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/ssense-exclusive-silver-3108-hoop-earring/10411761',
    's-text': 'Numbering',
    's-text 2': 'SSENSE Exclusive Silver #3108 Hoop Earring',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411701',
      name: 'SSENSE Exclusive Black #3117 Ear Cuff',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 95,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/ssense-exclusive-black-3117-ear-cuff/10411701',
      },
      url: '/men/product/numbering/ssense-exclusive-black-3117-ear-cuff/10411701',
      image: 'https://img.ssensemedia.com/images/222439M144003_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/ssense-exclusive-black-3117-ear-cuff/10411701',
    's-text': 'Numbering',
    's-text 2': 'SSENSE Exclusive Black #3117 Ear Cuff',
    's-text 3': '$95',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10413021',
      name: 'Silver #3160 Stud Earrings',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 130,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-3160-stud-earrings/10413021',
      },
      url: '/men/product/numbering/silver-3160-stud-earrings/10413021',
      image: 'https://img.ssensemedia.com/images/222439M144008_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-3160-stud-earrings/10413021',
    's-text': 'Numbering',
    's-text 2': 'Silver #3160 Stud Earrings',
    's-text 3': '$130',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10413031',
      name: 'Gold #3160 Stud Earrings',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 130,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/gold-3160-stud-earrings/10413031',
      },
      url: '/men/product/numbering/gold-3160-stud-earrings/10413031',
      image: 'https://img.ssensemedia.com/images/222439M144009_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/gold-3160-stud-earrings/10413031',
    's-text': 'Numbering',
    's-text 2': 'Gold #3160 Stud Earrings',
    's-text 3': '$130',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10413051',
      name: 'Silver #3214 Hoop Earrings',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 140,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-3214-hoop-earrings/10413051',
      },
      url: '/men/product/numbering/silver-3214-hoop-earrings/10413051',
      image: 'https://img.ssensemedia.com/images/222439M144011_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-3214-hoop-earrings/10413051',
    's-text': 'Numbering',
    's-text 2': 'Silver #3214 Hoop Earrings',
    's-text 3': '$140',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10001541',
      name: 'Silver & Black Jeweled Signet Ring',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 350,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/silver-and-black-jeweled-signet-ring/10001541',
      },
      url: '/men/product/alexander-mcqueen/silver-and-black-jeweled-signet-ring/10001541',
      image: 'https://img.ssensemedia.com/images/222259M147020_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/silver-and-black-jeweled-signet-ring/10001541',
    's-text': 'Alexander McQueen',
    's-text 2': 'Silver & Black Jeweled Signet Ring',
    's-text 3': '$350',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10001551',
      name: 'Silver Jeweled Signet Ring',
      brand: {
        '@type': 'Brand',
        name: 'alexander-mcqueen',
      },
      offers: {
        '@type': 'Offer',
        price: 350,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/alexander-mcqueen/silver-jeweled-signet-ring/10001551',
      },
      url: '/men/product/alexander-mcqueen/silver-jeweled-signet-ring/10001551',
      image: 'https://img.ssensemedia.com/images/222259M147021_1/alexander-mcqueen-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/alexander-mcqueen/silver-jeweled-signet-ring/10001551',
    's-text': 'Alexander McQueen',
    's-text 2': 'Silver Jeweled Signet Ring',
    's-text 3': '$350',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10411601',
      name: 'Silver #9071 Ring',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 110,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-9071-ring/10411601',
      },
      url: '/men/product/numbering/silver-9071-ring/10411601',
      image: 'https://img.ssensemedia.com/images/222439M147000_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-9071-ring/10411601',
    's-text': 'Numbering',
    's-text 2': 'Silver #9071 Ring',
    's-text 3': '$110',
  },
  {
    'plp-products__product-tile': {
      '@type': 'Product',
      productID: '10413141',
      name: 'Silver #5400 Ring',
      brand: {
        '@type': 'Brand',
        name: 'numbering',
      },
      offers: {
        '@type': 'Offer',
        price: 120,
        priceCurrency: 'USE',
        availability: 'https://schema.org/InStock',
        url: '/men/product/numbering/silver-5400-ring/10413141',
      },
      url: '/men/product/numbering/silver-5400-ring/10413141',
      image: 'https://img.ssensemedia.com/images/222439M147003_1/numbering-undefined.jpg',
    },
    'plp-products__product-tile href': 'https://www.ssense.com/en-in/men/product/numbering/silver-5400-ring/10413141',
    's-text': 'Numbering',
    's-text 2': 'Silver #5400 Ring',
    's-text 3': '$120',
  },
]